# Generated by Django 6.1.1 on 2026-09-28 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_rename_date_joined_user_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='userroleassignment',
            table='user_roles',
        ),
    ]
