# Generated by Django 6.1.1 on 2026-09-28 08:29

import apps.common.storage
import apps.registrations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationapplication',
            name='middle_initial',
            field=models.CharField(blank=True, max_length=4),
        ),
        migrations.AlterField(
            model_name='registrationapplication',
            name='id_document',
            field=models.ImageField(max_length=500, storage=apps.common.storage.get_resident_id_storage, upload_to=apps.registrations.models.id_document_upload_to),
        ),
    ]
