# Generated by Django 6.1.1 on 2026-09-29 04:56

import apps.registrations.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrations', '0002_registrationapplication_middle_initial_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='registrationapplication',
            name='reference_no',
            field=models.CharField(default=apps.registrations.models.generate_reference_no, editable=False, help_text='Reference number in format: MVA-{year}-{8 char random code}', max_length=20, unique=True),
        ),
    ]
