# Generated by Django 6.1.1 on 2026-09-28 03:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='owner_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='units', to='residents.resident'),
        ),
    ]
