# Generated by Django 6.1.1 on 2026-09-28 08:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0002_unit_owner_id'),
        ('registrations', '0002_registrationapplication_middle_initial_and_more'),
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Unit',
            new_name='Property',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='owner_id',
            new_name='owner',
        ),
        migrations.AlterModelTable(
            name='property',
            table='properties',
        ),
    ]
