# Generated by Django 6.1.1 on 2026-09-28 19:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_rename_unit_property_rename_owner_id_property_owner_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='property',
            old_name='unit_number',
            new_name='block_and_lot',
        ),
        migrations.RenameField(
            model_name='property',
            old_name='address',
            new_name='street_address',
        ),
    ]
