# Generated by Django 6.1.1 on 2026-09-28 08:29

import apps.common.storage
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0003_rename_unit_property_rename_owner_id_property_owner_and_more'),
        ('residents', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='approved_at',
        ),
        migrations.RemoveField(
            model_name='resident',
            name='approved_by',
        ),
        migrations.AddField(
            model_name='resident',
            name='id_document',
            field=models.ImageField(default=1, max_length=500, storage=apps.common.storage.get_resident_id_storage, upload_to=apps.common.storage.id_document_upload_to),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='resident',
            name='unit',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='residents', to='properties.property'),
        ),
    ]
