# Generated by Django 6.1.1 on 2026-09-30 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('residents', '0002_remove_resident_approved_at_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resident',
            name='move_in_date',
        ),
    ]
